### ISSUE TITLE
Fail to build 

### ISSUE THREAD

**Issue by manaoton** [ScRiPt1337/Leafyware-ransomware#2]
Traceback (most recent call last):
  File "builder.py", line 48, in <module>
    startbuilding(deathnote,"cryptpath",host,wallpaper)
  File "builder.py", line 31, in startbuilding
    writeline(94, '     var note = "'+deathnote+'"')                    File "builder.py", line 23, in writeline                                a_file = open(homepath + "\\ninja\\main.go", "r")                 FileNotFoundError: [Errno 2] No such file or directory: '/root/Music/Leafyware-ransomware/Builder\\ninja\\main.go'     

                     root@localhost:~/Music/Leafyware-ransomware/Builder#

**Comment by ScRiPt1337** [comment]
its happed because of the path  /root/Music/Leafyware-ransomware/Builder ( \ninja\main.go )  try it on a windows machine
